[package]
name = "rlup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.19", features = ["derive"] }
futures = "0.3"
async-std = "1.12.0"
rand = "0.8.5"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"